---
apiVersion: v1
kind: Namespace
metadata:
  name: test-dp
  labels:
    platform.tibco.com/dataplane-id: csuqggjdf96cgjlm92lg
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tibcoplatform
  namespace: default
spec:
  interval: 1m0s
  url: https://tibcosoftware.github.io/tp-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dp-configure-namespace
  namespace: test-dp
spec:
  interval: 1m0s
  releaseName: dp-configure-namespace
  chart:
    spec:
      chart: dp-configure-namespace
      sourceRef:
        kind: HelmRepository
        name: tp-helm-charts
        namespace: flux-system
      version: 1.3.4
  values:
    global:
      tibco:
        dataPlaneId: csuqggjdf96cgjlm92lg
        primaryNamespaceName: test-dp
        serviceAccount: test-dp
        enableClusterScopedPerm: false
        
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dp-core-infrastructure
  namespace: test-dp
spec:
  interval: 1m0s
  releaseName: dp-core-infrastructure
  chart:
    spec:
      chart: dp-core-infrastructure
      sourceRef:
        kind: HelmRepository
        name: tp-helm-charts
        namespace: flux-system
      version: 1.3.16
  values:
    global:
      tibco:
        dataPlaneId: csuqggjdf96cgjlm92lg
        subscriptionId: cpgo0sb8ook60pv3bfo0
        serviceAccount: test-dp
        containerRegistry:
          url: csgprdeuwrepoedge.jfrog.io
          repository: tibco-platform-docker-prod
          email: tibco-plt@cloud.com
      proxy:
        noProxy: ''
      logging:
        fluentbit:
          enabled: false
    tp-tibtunnel:
      configure:
        accessKey: 4P/v8bFU4uHYdHCVCKA1/nc9ojhyKrM/2IUNcWfUJVc
      connect:
        url: https://pmats.eu-west.tunnel.tibco.com/sub-cpgo0sb8ook60pv3bfo0-dp-csuqggjdf96cgjlm92lg
